# Generated by Django 2.1.7 on 2019-02-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_grad_freshmen', models.IntegerField()),
                ('u_grad_sophomore', models.IntegerField()),
                ('u_grad_junior', models.IntegerField()),
                ('u_grad_senior', models.IntegerField()),
                ('grad_ms_year_one', models.IntegerField()),
                ('grad_ms_year_two', models.IntegerField()),
            ],
        ),
    ]
