# Generated by Django 2.1.7 on 2019-02-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(choices=[('ap', 'Apples'), ('pn', 'Pineapples'), ('or', 'Oranges'), ('bn', 'Bananas')], default='ap', max_length=2)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
    ]
